% Import Raw Text Files
InputPath = uigetdir;
Files = dir([InputPath '/*.txt']);
OutputPath = uigetdir(pwd);
Text2mat(InputPath,OutputPath,Files);

function Text2mat(InputPath,OutputPath,Files)
    for i = 1:length(Files)
        TextFile = importdata(fullfile(InputPath,Files(i,1).name)); % fullfile including path
        OneSpectrum = struct('Spectrum',TextFile.data(:,2),...
            'Date',erase(TextFile.textdata{2,:},'Date: '),...
            'Integration',str2double(erase(TextFile.textdata{6,:},'Integration Time (sec): ')),...
            'Scan2Average',str2double(erase(TextFile.textdata{7,:},'Scans to average: ')),...
            'PatientID','not available',...
            'SessionNumber','not available',...
            'SessionName','not available');
        save([OutputPath '/' erase(Files(i,1).name,'.txt') '.mat'],'OneSpectrum');
    end
end
