% Import Text Files
[RawFile,InputPath] = uigetfile('*.txt','Select the files of interest','MultiSelect', 'on');
OutputPath = uigetdir(pwd);

if iscell(RawFile)
    for i = 1:length(RawFile)
        TextFile = importdata(fullfile(InputPath,RawFile{i})); % fullfile including path
        OneSpectrum = struct('Spectrum',TextFile.data(:,2),...
                            'Date',erase(TextFile.textdata{2,:},'Date: '),...
                            'Integration',str2double(erase(TextFile.textdata{6,:},'Integration Time (sec): ')),...
                            'Scan2Average',str2double(erase(TextFile.textdata{7,:},'Scans to average: ')),...
                            'PatientID','not available',...
                            'SessionNumber','not available',...
                            'SessionName','not available');
         save([OutputPath '/' erase(RawFile{1,i},'.txt') '.mat'],'OneSpectrum');
    end
else
    TextFile = importdata(fullfile(InputPath,RawFile));
    OneSpectrum = struct('Spectrum',TextFile.data(:,2),...
        'Date',erase(TextFile.textdata{2,:},'Date: '),...
        'Integration',str2double(erase(TextFile.textdata{6,:},'Integration Time (sec): ')),...
        'Scan2Average',str2double(erase(TextFile.textdata{7,:},'Scans to average: ')),...
        'PatientID','not available',...
        'SessionNumber','not available',...
        'SessionName','not available');
    save([OutputPath '/' erase(RawFile,'.txt') '.mat'],'OneSpectrum');
end